/* Kolejka wpisów na blog (Inspiracje). Każdy wpis pokazuje się sam w dniu z pola "date" (RRRR-MM-DD),
   na stronie Inspiracje i w kafelkach bloga na stronie głównej – we wszystkich językach.
   Nowy wpis: dopisz obiekt na końcu listy (teksty pl/en/de/cs, zdjęcie z produktu lub z img/foto/).
   Tagi = zakładki na stronie Inspiracje: porzadek (Organizacja), eko (Ekologia), garaz (Garaż i biuro), pomniki (Pomniki). */
window.IH_BLOG_TAGS = {
  porzadek: { pl: "Organizacja", en: "Organisation", de: "Organisation", cs: "Organizace" },
  eko: { pl: "Ekologia", en: "Ecology", de: "Umwelt", cs: "Ekologie" },
  garaz: { pl: "Garaż i biuro", en: "Garage and office", de: "Garage und Büro", cs: "Garáž a kancelář" },
  pomniki: { pl: "Pomniki", en: "Headstones", de: "Grabsteine", cs: "Pomníky" }
};
window.IH_BLOG = [
  {
    id: "jaki-worek-do-kosza", date: "2026-10-09", tag: "porzadek", min: 4,
    img: "https://cdn.shopify.com/s/files/1/1032/1985/5705/files/661e3e195e43bd2d3d87927d_worki-ldpe-60l-czarny-50szt.jpg?v=1776083371&width=1200",
    alt: { pl: "Kobieta w rękawicach wymienia worek w koszu na śmieci w kuchni", en: "A woman in gloves changing the bag in a kitchen bin", de: "Eine Frau mit Handschuhen wechselt den Beutel im Küchenmülleimer", cs: "Žena v rukavicích vyměňuje pytel v kuchyňském koši" },
    title: { pl: "Jaki worek do kosza? Pojemność i grubość bez zgadywania", en: "Which bin bag? Capacity and thickness without guesswork", de: "Welcher Müllbeutel? Volumen und Stärke ohne Rätselraten", cs: "Jaký pytel do koše? Objem a tloušťka bez hádání" },
    lead: { pl: "Za mały worek pęka przy wiązaniu, za duży zsuwa się do środka kosza. Trzy proste zasady pomogą dobrać właściwy.", en: "A bag that's too small splits when you tie it; one that's too big slides into the bin. Three simple rules help you pick the right one.", de: "Ein zu kleiner Beutel reißt beim Zubinden, ein zu großer rutscht in den Eimer. Drei einfache Regeln helfen bei der Wahl.", cs: "Příliš malý pytel praskne při zavazování, příliš velký sklouzne do koše. Tři jednoduchá pravidla pomohou vybrat ten správný." },
    steps: {
      pl: ["Sprawdź pojemność kosza – zwykle jest na dnie. Worek powinien mieć tyle samo litrów albo trochę więcej.", "Do łazienki i biura wystarczą cienkie worki 20–35 l. Do kuchni najlepiej sprawdzają się worki 35–60 l.", "Na liście, gruz i ciężkie odpady wybierz worki mocne albo ekstra mocne 120–240 l – grubsza folia nie przebije się na gałęziach.", "Jeśli segregujesz odpady, wybierz worki w kolorach frakcji. Od razu widać, co gdzie wrzucić."],
      en: ["Check the bin's capacity – it's usually on the bottom. The bag should have the same number of litres or slightly more.", "Thin 20–35 l bags are enough for the bathroom and office. 35–60 l bags work best in the kitchen.", "For leaves, rubble and heavy waste choose strong or extra-strong 120–240 l bags – the thicker film won't tear on branches.", "If you sort your waste, choose bags in the colours of each fraction. You can see at a glance what goes where."],
      de: ["Prüfen Sie das Volumen des Eimers – es steht meist auf dem Boden. Der Beutel sollte gleich viele Liter oder etwas mehr haben.", "Für Bad und Büro reichen dünne Beutel mit 20–35 l. In der Küche bewähren sich 35–60 l.", "Für Laub, Schutt und schwere Abfälle wählen Sie starke oder extrastarke Beutel mit 120–240 l – die dickere Folie reißt auch an Ästen nicht.", "Wenn Sie Müll trennen, wählen Sie Beutel in den Farben der Fraktionen. So sieht man sofort, was wohin gehört."],
      cs: ["Zkontrolujte objem koše – bývá uvedený na dně. Pytel by měl mít stejný počet litrů nebo o něco víc.", "Do koupelny a kanceláře stačí tenké pytle 20–35 l. Do kuchyně se nejlépe hodí pytle 35–60 l.", "Na listí, suť a těžký odpad zvolte pevné nebo extra pevné pytle 120–240 l – silnější fólie se o větve neprotrhne.", "Pokud třídíte odpad, vyberte pytle v barvách jednotlivých složek. Hned je vidět, co kam patří."]
    },
    links: [{ href: "produkty.html#worki", dark: true, label: { pl: "Worki na odpady", en: "Bin bags", de: "Müllbeutel", cs: "Pytle na odpadky" } }]
  },
  {
    id: "jesienne-porzadki-w-ogrodzie", date: "2026-10-13", tag: "porzadek", min: 4,
    img: "https://cdn.shopify.com/s/files/1/1032/1985/5705/files/661e3dea5e43bd2d3d83b20d_worki-ldpe-120l-czarny-25szt.jpg?v=1776083369&width=1200",
    alt: { pl: "Pełny czarny worek niesiony przez ogród w jesiennym słońcu", en: "A full black bag carried through the garden in autumn sun", de: "Ein voller schwarzer Beutel wird in der Herbstsonne durch den Garten getragen", cs: "Plný černý pytel nesený zahradou v podzimním slunci" },
    title: { pl: "Jesienne porządki w ogrodzie: plan na jedno popołudnie", en: "Autumn garden clean-up: a plan for one afternoon", de: "Herbstputz im Garten: ein Plan für einen Nachmittag", cs: "Podzimní úklid zahrady: plán na jedno odpoledne" },
    lead: { pl: "Zanim przyjdą przymrozki, warto uprzątnąć ogród i taras. Z dobrym planem zajmie to kilka godzin.", en: "Before the frost arrives, it's worth tidying the garden and patio. With a good plan it takes just a few hours.", de: "Bevor der Frost kommt, lohnt es sich, Garten und Terrasse aufzuräumen. Mit einem guten Plan dauert das nur wenige Stunden.", cs: "Než přijdou mrazíky, vyplatí se uklidit zahradu a terasu. S dobrým plánem to zabere jen pár hodin." },
    steps: {
      pl: ["Zgrabiaj liście zaraz po deszczu, kiedy są ciężkie i nie rozwiewa ich wiatr.", "Liście i drobne gałęzie zbieraj do worków 120 l albo 240 l. Mocna folia wytrzyma ostre patyki.", "Meble ogrodowe umyj, osusz i schowaj albo przykryj. Drobiazgi z tarasu zapakuj do pojemników z pokrywą.", "Na koniec zawieś karmnik – ptaki szybko zapamiętają nowe miejsce przed zimą."],
      en: ["Rake leaves straight after rain, when they're heavy and the wind doesn't scatter them.", "Collect leaves and small branches in 120 l or 240 l bags. Strong film can handle sharp twigs.", "Wash, dry and store or cover the garden furniture. Pack small patio items into lidded boxes.", "Finally, hang up a bird feeder – birds will quickly remember the new spot before winter."],
      de: ["Rechen Sie das Laub direkt nach dem Regen, wenn es schwer ist und der Wind es nicht verweht.", "Sammeln Sie Laub und kleine Äste in 120-l- oder 240-l-Beuteln. Starke Folie hält auch spitzen Zweigen stand.", "Gartenmöbel waschen, trocknen und verstauen oder abdecken. Kleinteile von der Terrasse in Boxen mit Deckel packen.", "Zum Schluss ein Futterhaus aufhängen – Vögel merken sich den neuen Platz schnell vor dem Winter."],
      cs: ["Listí hrabejte hned po dešti, kdy je těžké a vítr ho nerozfouká.", "Listí a drobné větve sbírejte do pytlů 120 l nebo 240 l. Pevná fólie vydrží i ostré klacíky.", "Zahradní nábytek umyjte, osušte a uložte nebo zakryjte. Drobnosti z terasy zabalte do boxů s víkem.", "Nakonec zavěste krmítko – ptáci si nové místo před zimou rychle zapamatují."]
    },
    links: [{ href: "produkty.html#worki", dark: true, label: { pl: "Worki 120 i 240 l", en: "120 and 240 l bags", de: "Beutel 120 und 240 l", cs: "Pytle 120 a 240 l" } }, { href: "produkty.html#budki", label: { pl: "Karmniki", en: "Bird feeders", de: "Futterhäuser", cs: "Krmítka" } }]
  },
  {
    id: "pomnik-przed-1-listopada", date: "2026-10-16", tag: "pomniki", min: 4,
    img: "https://cdn.shopify.com/s/files/1/1032/1985/5705/files/634871d8bf402dffb9c29bac_zestaw-do-renowacji-zotych-napisw-na-pomnikach.jpg?v=1776342226&width=1200",
    alt: { pl: "Odnawianie złotych liter na nagrobku markerem z zestawu IDEA HOME", en: "Restoring gold letters on a headstone with the IDEA HOME kit marker", de: "Auffrischen goldener Buchstaben auf einem Grabstein mit dem Marker aus dem IDEA HOME Set", cs: "Obnova zlatých písmen na náhrobku fixem ze sady IDEA HOME" },
    title: { pl: "Pomnik przed 1 listopada: czyszczenie i odnowienie napisów", en: "Headstone care before All Saints' Day: cleaning and restoring inscriptions", de: "Grabpflege vor Allerheiligen: Reinigen und Inschriften auffrischen", cs: "Hrob před Dušičkami: čištění a obnova nápisů" },
    lead: { pl: "Najlepiej zająć się pomnikiem 1–2 tygodnie przed świętem, w suchy i pochmurny dzień. Wystarczą dwa kroki.", en: "It's best to see to the headstone 1–2 weeks before the holiday, on a dry, cloudy day. Two steps are enough.", de: "Am besten kümmern Sie sich 1–2 Wochen vor dem Feiertag an einem trockenen, bewölkten Tag um den Grabstein. Zwei Schritte genügen.", cs: "Nejlépe je postarat se o pomník 1–2 týdny před svátkem, za suchého a zataženého dne. Stačí dva kroky." },
    steps: {
      pl: ["Najpierw umyj kamień aktywną pianą: nanieś ją równą warstwą, odczekaj kilka minut i zetrzyj wilgotną ściereczką.", "Gdy kamień wyschnie, delikatnie oczyść litery dołączonym pumeksem, żeby farba dobrze się trzymała.", "Markerem z zestawu obrysuj litery od środka do krawędzi. Wybierz kolor napisów: złoty, srebrny, biały albo czarny.", "Daj farbie wyschnąć zgodnie z instrukcją, zanim postawisz znicze i kwiaty."],
      en: ["First wash the stone with the active foam: apply an even layer, wait a few minutes and wipe with a damp cloth.", "Once the stone is dry, gently clean the letters with the pumice included so the paint adheres well.", "Trace the letters with the kit's marker from the centre to the edges. Choose the inscription colour: gold, silver, white or black.", "Let the paint dry as instructed before placing candles and flowers."],
      de: ["Reinigen Sie den Stein zuerst mit dem Aktivschaum: gleichmäßig auftragen, einige Minuten warten und mit einem feuchten Tuch abwischen.", "Wenn der Stein trocken ist, die Buchstaben vorsichtig mit dem beiliegenden Bimsstein säubern, damit die Farbe gut haftet.", "Die Buchstaben mit dem Marker aus dem Set von der Mitte zum Rand nachziehen. Wählen Sie die Farbe: Gold, Silber, Weiß oder Schwarz.", "Die Farbe gemäß Anleitung trocknen lassen, bevor Sie Grablichter und Blumen aufstellen."],
      cs: ["Nejdřív kámen umyjte aktivní pěnou: naneste rovnoměrnou vrstvu, počkejte několik minut a setřete vlhkou utěrkou.", "Až kámen uschne, písmena jemně očistěte přiloženou pemzou, aby barva dobře držela.", "Fixem ze sady obtahujte písmena od středu k okrajům. Vyberte barvu nápisů: zlatou, stříbrnou, bílou nebo černou.", "Než postavíte svíčky a květiny, nechte barvu zaschnout podle návodu."]
    },
    links: [{ href: "produkty.html#nagrobki", dark: true, label: { pl: "Piana i zestawy do renowacji", en: "Foam and renovation kits", de: "Schaum und Renovierungssets", cs: "Pěna a renovační sady" } }]
  },
  {
    id: "garaz-z-techbox", date: "2026-10-20", tag: "garaz", min: 3,
    img: "https://cdn.shopify.com/s/files/1/1032/1985/5705/files/675809cee524fb70b6f0528a_insert-do-pojemnika-techbox-hd-ih-4055l-czarny.jpg?v=1776083516&width=1200",
    alt: { pl: "Otwarte pojemniki Techbox pełne narzędzi, taśm i drobiazgów", en: "Open Techbox boxes full of tools, tapes and small parts", de: "Offene Techbox-Boxen voller Werkzeuge, Klebebänder und Kleinteile", cs: "Otevřené boxy Techbox plné nářadí, pásek a drobností" },
    title: { pl: "Garaż przed zimą: wszystko w pojemnikach, nic na podłodze", en: "Garage before winter: everything in boxes, nothing on the floor", de: "Garage vor dem Winter: alles in Boxen, nichts auf dem Boden", cs: "Garáž před zimou: vše v boxech, nic na podlaze" },
    lead: { pl: "Zimą w garażu stoi auto, sanki i opony. Żeby wszystko się zmieściło, drobiazgi muszą trafić do pojemników.", en: "In winter the garage holds the car, sledges and tyres. To fit everything in, the small stuff has to go into boxes.", de: "Im Winter stehen in der Garage Auto, Schlitten und Reifen. Damit alles passt, müssen Kleinteile in Boxen.", cs: "V zimě je v garáži auto, sáňky a pneumatiky. Aby se vše vešlo, drobnosti musí do boxů." },
    steps: {
      pl: ["Podziel rzeczy na grupy: narzędzia, akcesoria do auta, ogród, sport.", "Każdą grupę włóż do osobnego pojemnika z pokrywą. Wkład z przegródkami pomieści śruby, taśmy i drobne narzędzia.", "Pojemniki ustaw jeden na drugim przy ścianie – zyskasz miejsce na podłodze.", "Podpisz pojemniki od frontu, żeby nie otwierać wszystkich po kolei."],
      en: ["Divide things into groups: tools, car accessories, garden, sport.", "Put each group into a separate lidded box. A compartment insert holds screws, tapes and small tools.", "Stack the boxes against the wall – you'll gain floor space.", "Label the boxes on the front so you don't have to open them one by one."],
      de: ["Teilen Sie alles in Gruppen: Werkzeug, Autozubehör, Garten, Sport.", "Jede Gruppe kommt in eine eigene Box mit Deckel. Ein Einsatz mit Fächern fasst Schrauben, Klebebänder und Kleinwerkzeug.", "Stapeln Sie die Boxen an der Wand – so gewinnen Sie Platz auf dem Boden.", "Beschriften Sie die Boxen vorne, damit Sie nicht alle nacheinander öffnen müssen."],
      cs: ["Rozdělte věci do skupin: nářadí, doplňky do auta, zahrada, sport.", "Každou skupinu dejte do samostatného boxu s víkem. Vložka s přihrádkami pojme šrouby, pásky a drobné nářadí.", "Boxy postavte na sebe ke zdi – získáte místo na podlaze.", "Boxy popište zepředu, abyste je nemuseli otevírat jeden po druhém."]
    },
    links: [{ href: "produkty.html#techbox", dark: true, label: { pl: "Pojemniki Techbox", en: "Techbox boxes", de: "Techbox-Boxen", cs: "Boxy Techbox" } }, { href: "produkty.html#warsztat", label: { pl: "Taśmy i sznurki", en: "Tapes and twine", de: "Klebebänder und Schnüre", cs: "Pásky a provázky" } }]
  },
  {
    id: "karmnik-na-zime", date: "2026-10-23", tag: "eko", min: 3,
    img: "https://cdn.shopify.com/s/files/1/1032/1985/5705/files/6348579abf402dffb9dd8dd4_karmnik-dla-ptakw-ih-maxi.jpg?v=1776082941&width=1200",
    alt: { pl: "Drewniany karmnik IDEA HOME z sikorkami i dzięciołem zimą", en: "IDEA HOME wooden bird feeder with tits and a woodpecker in winter", de: "IDEA HOME Holz-Futterhaus mit Meisen und Specht im Winter", cs: "Dřevěné krmítko IDEA HOME se sýkorkami a datlem v zimě" },
    title: { pl: "Karmnik na zimę: gdzie go powiesić i czym karmić ptaki", en: "A bird feeder for winter: where to hang it and what to feed", de: "Futterhaus für den Winter: wo aufhängen und was füttern", cs: "Krmítko na zimu: kam ho pověsit a čím krmit" },
    lead: { pl: "Ptaki najbardziej potrzebują pomocy przy mrozie i śniegu. Kilka zasad sprawi, że karmnik będzie dla nich bezpieczny.", en: "Birds need help most in frost and snow. A few rules make the feeder safe for them.", de: "Vögel brauchen bei Frost und Schnee am meisten Hilfe. Ein paar Regeln machen das Futterhaus für sie sicher.", cs: "Ptáci nejvíc potřebují pomoc v mrazu a sněhu. Několik pravidel zajistí, že krmítko pro ně bude bezpečné." },
    steps: {
      pl: ["Powieś karmnik na wysokości ok. 1,5–2 m, z dala od krzewów, w których mogą czaić się koty.", "Wybierz miejsce osłonięte od wiatru i widoczne z okna – będziesz mieć codzienny podgląd gości.", "Podawaj słonecznik, ziarna i nieprzetworzony smalec lub łój. Nie dawaj chleba ani solonych resztek.", "Karmienie zacznij przy pierwszych przymrozkach i prowadź regularnie aż do wiosny. Raz na jakiś czas wyczyść karmnik."],
      en: ["Hang the feeder about 1.5–2 m high, away from shrubs where cats can hide.", "Pick a spot sheltered from the wind and visible from a window – you'll get a daily view of your visitors.", "Offer sunflower seeds, grains and unprocessed lard or suet. Don't give bread or salted leftovers.", "Start feeding with the first frosts and keep it regular until spring. Clean the feeder now and then."],
      de: ["Hängen Sie das Futterhaus in etwa 1,5–2 m Höhe auf, weg von Sträuchern, in denen Katzen lauern können.", "Wählen Sie einen windgeschützten Platz, den Sie vom Fenster aus sehen – so haben Sie täglich Besuch im Blick.", "Füttern Sie Sonnenblumenkerne, Körner und unbehandeltes Schmalz oder Talg. Kein Brot und keine salzigen Reste.", "Beginnen Sie mit den ersten Frösten und füttern Sie regelmäßig bis zum Frühling. Reinigen Sie das Futterhaus ab und zu."],
      cs: ["Krmítko zavěste do výšky asi 1,5–2 m, dál od keřů, ve kterých se mohou skrývat kočky.", "Vyberte místo chráněné před větrem a viditelné z okna – budete mít denní přehled o návštěvnících.", "Nabízejte slunečnici, zrní a nesolené sádlo nebo lůj. Nedávejte chléb ani slané zbytky.", "Krmit začněte s prvními mrazíky a pokračujte pravidelně až do jara. Občas krmítko vyčistěte."]
    },
    links: [{ href: "produkty.html#budki", dark: true, label: { pl: "Budki i karmniki", en: "Birdhouses and feeders", de: "Nistkästen und Futterhäuser", cs: "Budky a krmítka" } }]
  },
  {
    id: "szafa-na-zime", date: "2026-10-27", tag: "porzadek", min: 4,
    img: "https://cdn.shopify.com/s/files/1/1032/1985/5705/files/67a9cb3082076a6222b61f0c_pojemnik-ih-flexistore-mix-rozmiarw-4szt-denim.jpg?v=1776083537&width=1200",
    alt: { pl: "Pojemniki Flexistore z kocami w jasnym wnętrzu", en: "Flexistore boxes with blankets in a bright interior", de: "Flexistore-Boxen mit Decken in einem hellen Raum", cs: "Boxy Flexistore s dekami ve světlém interiéru" },
    title: { pl: "Szafa na zimę: jak schować letnie ubrania, żeby przetrwały do wiosny", en: "Winter wardrobe: how to store summer clothes until spring", de: "Kleiderschrank für den Winter: Sommerkleidung richtig verstauen", cs: "Šatník na zimu: jak uložit letní oblečení do jara" },
    lead: { pl: "Zmiana garderoby to dobry moment na porządki. Letnie rzeczy warto schować tak, żeby wiosną były gotowe do noszenia.", en: "Switching wardrobes is a good moment to tidy up. Store summer clothes so they're ready to wear in spring.", de: "Der Garderobenwechsel ist ein guter Moment zum Aufräumen. Verstauen Sie Sommerkleidung so, dass sie im Frühling bereit ist.", cs: "Výměna šatníku je dobrá chvíle na úklid. Letní věci uložte tak, aby byly na jaře připravené k nošení." },
    steps: {
      pl: ["Przed schowaniem wypierz i dokładnie wysusz wszystkie ubrania – wilgoć to największy wróg przechowywania.", "Odłóż rzeczy, których nie nosiłaś(-eś) przez cały sezon. Może czas je komuś oddać?", "Ubrania złóż i włóż do pojemników z pokrywą: lekkie do większych, buty i dodatki do mniejszych.", "Pojemniki ustaw na górnej półce albo pod łóżkiem i opisz zawartość na froncie."],
      en: ["Before storing, wash and dry all clothes thoroughly – moisture is storage's worst enemy.", "Set aside anything you didn't wear all season. Maybe it's time to give it away?", "Fold the clothes into lidded boxes: light items in larger boxes, shoes and accessories in smaller ones.", "Put the boxes on the top shelf or under the bed and label the contents on the front."],
      de: ["Waschen und trocknen Sie alle Kleidungsstücke vor dem Verstauen gründlich – Feuchtigkeit ist der größte Feind.", "Legen Sie beiseite, was Sie die ganze Saison nicht getragen haben. Vielleicht ist es Zeit, es weiterzugeben?", "Kleidung falten und in Boxen mit Deckel legen: Leichtes in größere, Schuhe und Accessoires in kleinere.", "Die Boxen ins oberste Fach oder unters Bett stellen und den Inhalt vorne beschriften."],
      cs: ["Před uložením všechno oblečení vyperte a důkladně usušte – vlhkost je největší nepřítel skladování.", "Odložte věci, které jste celou sezónu nenosili. Možná je čas je někomu darovat?", "Oblečení složte do boxů s víkem: lehké věci do větších, boty a doplňky do menších.", "Boxy postavte na horní polici nebo pod postel a obsah popište zepředu."]
    },
    links: [{ href: "produkty.html#flexistore", dark: true, label: { pl: "Pojemniki Flexistore", en: "Flexistore boxes", de: "Flexistore-Boxen", cs: "Boxy Flexistore" } }, { href: "produkty.html#garderoba", label: { pl: "Do garderoby", en: "For the wardrobe", de: "Für den Kleiderschrank", cs: "Do šatny" } }]
  },
  {
    id: "mydlo-w-kanistrze", date: "2026-10-30", tag: "porzadek", min: 3,
    img: "https://cdn.shopify.com/s/files/1/1032/1985/5705/files/4c7e7ae53b32b56db85b5c49c49f7011.jpg?v=1776342322&width=1200",
    alt: { pl: "Uzupełnianie butelki z dozownikiem mydłem RAKUN z kanistra 5 l", en: "Refilling a dispenser bottle with RAKUN soap from a 5 l canister", de: "Nachfüllen einer Spenderflasche mit RAKUN Seife aus dem 5-l-Kanister", cs: "Doplňování lahve s dávkovačem mýdlem RAKUN z 5l kanystru" },
    title: { pl: "Mydło w kanistrze: jak wygodnie uzupełniać dozowniki", en: "Soap in a canister: how to refill dispensers easily", de: "Seife im Kanister: Spender bequem nachfüllen", cs: "Mýdlo v kanystru: jak pohodlně doplňovat dávkovače" },
    lead: { pl: "Kanister 5 l wystarcza na długo i sprawdza się w domu, biurze i małej firmie. Kilka trików ułatwi uzupełnianie.", en: "A 5 l canister lasts a long time and works well at home, in the office and in small businesses. A few tricks make refilling easier.", de: "Ein 5-l-Kanister reicht lange und bewährt sich zu Hause, im Büro und im kleinen Betrieb. Ein paar Tricks erleichtern das Nachfüllen.", cs: "Kanystr 5 l vydrží dlouho a hodí se domů, do kanceláře i malé firmy. Pár triků usnadní doplňování." },
    steps: {
      pl: ["Przed uzupełnieniem umyj i wysusz dozownik – wtedy mydło nie zmieni zapachu ani koloru.", "Nalewaj przez mały lejek, powoli i nad zlewem. Kanister trzymaj oburącz, uchwytem do góry.", "Nie napełniaj dozownika po brzegi – zostaw centymetr miejsca na pompkę.", "Kanister przechowuj zakręcony, w temperaturze pokojowej, z dala od słońca."],
      en: ["Wash and dry the dispenser before refilling – then the soap won't change scent or colour.", "Pour slowly through a small funnel over the sink. Hold the canister with both hands, handle up.", "Don't fill the dispenser to the brim – leave a centimetre of space for the pump.", "Keep the canister closed, at room temperature and out of the sun."],
      de: ["Spender vor dem Nachfüllen waschen und trocknen – so ändern sich Duft und Farbe der Seife nicht.", "Langsam über der Spüle durch einen kleinen Trichter einfüllen. Den Kanister mit beiden Händen halten, Griff nach oben.", "Den Spender nicht bis zum Rand füllen – einen Zentimeter Platz für die Pumpe lassen.", "Den Kanister geschlossen, bei Raumtemperatur und vor Sonne geschützt lagern."],
      cs: ["Před doplněním dávkovač umyjte a usušte – mýdlo pak nezmění vůni ani barvu.", "Nalévejte pomalu malým trychtýřem nad umyvadlem. Kanystr držte oběma rukama, úchytem nahoru.", "Dávkovač neplňte až po okraj – nechte centimetr místa pro pumpičku.", "Kanystr skladujte zavřený, při pokojové teplotě a mimo slunce."]
    },
    links: [{ href: "produkty.html#mydla", dark: true, label: { pl: "Mydła RAKUN", en: "RAKUN soaps", de: "RAKUN Seifen", cs: "Mýdla RAKUN" } }, { href: "rakun/index.html#mydla", label: { pl: "Seria RAKUN", en: "RAKUN range", de: "Serie RAKUN", cs: "Řada RAKUN" } }]
  },
  {
    id: "prezenty-w-papierowych-torbach", date: "2026-11-03", tag: "porzadek", min: 3,
    img: "https://cdn.shopify.com/s/files/1/1032/1985/5705/files/66bb2192e524fb70b6277c3b_pudeko-na-wino-ih-wave-kraft-clickgo-6szt.jpg?v=1776687722&width=1200",
    alt: { pl: "Papierowe pudełko na wino Wave Kraft w świątecznej aranżacji", en: "Wave Kraft paper wine box in a festive arrangement", de: "Wave Kraft Weinbox aus Papier in festlicher Dekoration", cs: "Papírová krabička na víno Wave Kraft ve sváteční aranžmá" },
    title: { pl: "Prezenty bez stresu: pakowanie w papierowe torby", en: "Stress-free gifts: wrapping in paper bags", de: "Geschenke ohne Stress: Verpacken in Papiertüten", cs: "Dárky bez stresu: balení do papírových tašek" },
    lead: { pl: "Do świąt zostało kilka tygodni. Papierowa torba to najszybszy sposób na elegancko zapakowany prezent – bez taśmy i nożyczek.", en: "The holidays are a few weeks away. A paper bag is the quickest way to an elegantly wrapped gift – no tape or scissors.", de: "Bis zu den Feiertagen sind es nur noch wenige Wochen. Eine Papiertüte ist der schnellste Weg zum elegant verpackten Geschenk – ohne Klebeband und Schere.", cs: "Do svátků zbývá pár týdnů. Papírová taška je nejrychlejší cesta k elegantně zabalenému dárku – bez pásky a nůžek." },
    steps: {
      pl: ["Dobierz rozmiar torby do prezentu: S na drobiazgi, M na książkę lub kosmetyki, L na sweter albo zestaw.", "Na dno połóż kartkę bibuły, a prezent przykryj drugą – ładnie wygląda i zasłania zawartość.", "Do uchwytu przywiąż bilecik na naturalnym sznurku.", "Wino zapakuj do pudełka na butelkę – jest stabilne i od razu gotowe do wręczenia."],
      en: ["Match the bag size to the gift: S for small items, M for a book or cosmetics, L for a jumper or a set.", "Put a sheet of tissue paper at the bottom and cover the gift with another – it looks nice and hides the contents.", "Tie a gift tag to the handle with natural twine.", "Pack wine in a bottle box – it's stable and ready to hand over."],
      de: ["Wählen Sie die Tütengröße passend zum Geschenk: S für Kleinigkeiten, M für ein Buch oder Kosmetik, L für einen Pullover oder ein Set.", "Ein Blatt Seidenpapier auf den Boden legen und das Geschenk mit einem zweiten abdecken – sieht schön aus und verdeckt den Inhalt.", "Ein Kärtchen mit Naturschnur am Henkel befestigen.", "Wein in eine Flaschenbox packen – sie steht stabil und ist sofort bereit zum Überreichen."],
      cs: ["Velikost tašky zvolte podle dárku: S na drobnosti, M na knihu nebo kosmetiku, L na svetr nebo sadu.", "Na dno dejte arch hedvábného papíru a dárek přikryjte dalším – vypadá to hezky a obsah není vidět.", "K uchu přivažte kartičku na přírodním provázku.", "Víno zabalte do krabičky na láhev – je stabilní a hned připravená k předání."]
    },
    links: [{ href: "produkty.html#prezenty", dark: true, label: { pl: "Opakowania prezentowe", en: "Gift packaging", de: "Geschenkverpackungen", cs: "Dárkové obaly" } }]
  }
];
